In [79]:
#Use a tuple to create a NumPy array:

import numpy as np

arr = np.array((1, 2, 3, 4, 5))

print(arr)

[1 2 3 4 5]


In [80]:
#Use a list to create a NumPy array:

import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


# Dimensions in Arrays
A dimension in arrays is one level of array depth (nested arrays).

nested array: are arrays that have arrays as their elements.

# 0-D Arrays
0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.

In [81]:
#Create a 0-D array with value 42

import numpy as np

arr = np.array(42)

print(arr)

42


In [82]:
#Create a 0-D array with value 52   ------> you can get any number in space of 52

import numpy as np

arr = np.array(52)

print(arr)

52


# 1-D Arrays
An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.

These are the most common and basic arrays.

In [83]:
#Create a 1-D array containing the values 1,2,3,4,5:

import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [84]:
#Create a 1-D array containing the values 42,56,42,45,82,1,65:

import numpy as np

arr = np.array([42,56,42,45,82,1,65])

print(arr)

[42 56 42 45 82  1 65]


# 2-D Arrays
An array that has 1-D arrays as its elements is called a 2-D array.

These are often used to represent matrix or 2nd order tensors.

NumPy has a whole sub module dedicated towards matrix operations called numpy.mat

In [85]:
#Create a 2-D array containing two arrays with the values 1,2,3 and 4,5,6:

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


In [86]:
#Create a 2-D array containing two arrays with the values 10,11,12 and 14,15,16:

import numpy as np

arr = np.array([[10, 11, 12], [14, 15, 16]])

print(arr)

[[10 11 12]
 [14 15 16]]


# 3-D arrays
An array that has 2-D arrays (matrices) as its elements is called 3-D array.

These are often used to represent a 3rd order tensor.

In [87]:
#Create a 3-D array with two 2-D arrays, both containing two arrays with the values 1,2,3 and 4,5,6:

import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [88]:
arr = np.array ([[[10,11,12],[13,14,15]],[[10,11,12],[13,14,15]]])
print(arr)

[[[10 11 12]
  [13 14 15]]

 [[10 11 12]
  [13 14 15]]]


# Check Number of Dimensions?
NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.

In [89]:
#Check how many dimensions the arrays have:

import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)  #----------> ndim use for check the number of dimensions
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


# Higher Dimensional Arrays
An array can have any number of dimensions.

When the array is created, you can define the number of dimensions by using the ndmin argument.

In [90]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)     #---------> ndmin for define the number of dimension 

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


# NumPy Array Indexing

Access Array Elements
Array indexing is the same as accessing an array element.

You can access an array element by referring to its index number.

The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.

# NumPy Array Slicing


Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].

If we don't pass start its considered 0

If we don't pass end its considered length of array in that dimension

If we don't pass step its considered 1

In [92]:
#Slice elements from index 1 to index 5 from the following array:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])
print(arr[:6:2])  #......... with step of two


[2 3 4 5]
[1 3 5]


# Data Types in Python




# Data Types in NumPy


NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

Below is a list of all data types in NumPy and the characters used to represent them.

i - integer
b - boolean
u - unsigned integer
f - float
c - complex float
m - timedelta
M - datetime
O - object
S - string
U - unicode string
V - fixed chunk of memory for other type ( void )


In [94]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int32


In [95]:
import numpy as np

arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


In [96]:
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [97]:
myarr = np.array((1, 2, 3, 4, 5)) 

In [98]:
myarr.shape   #...........>tell you coloumn and row  

(5,)

In [99]:
myarr.dtype

dtype('int32')

In [100]:
myarr

array([1, 2, 3, 4, 5])

In [101]:
myarr.size

5

In [102]:
lspace = np.linspace(1,50,10)
lspace

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [103]:
emp = np.empty((4,6))
emp

array([[8.48790684e-312, 7.80623720e-322, 0.00000000e+000,
        0.00000000e+000, 7.56593016e-307, 1.16095484e-028],
       [3.98568193e+252, 3.00966884e-153, 3.62485156e+228,
        1.69375267e+190, 1.17567366e+214, 8.50783470e-096],
       [4.08138229e+223, 8.44747281e+252, 7.23796664e+159,
        4.11083866e+223, 3.74168445e+233, 1.35717430e+131],
       [8.95402175e-096, 9.21780209e+135, 6.96770842e+252,
        1.04914409e-153, 9.78750380e+199, 6.97843734e+252]])

In [104]:
emp_like = np.empty_like(myarr)

In [105]:
emp_like

array([1, 2, 3, 4, 5])

In [106]:
x=[[1,2,3],[4,5,6],[7,1,0]]

In [107]:
ar = np.array(x)
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [108]:
ar.sum(axis=0)

array([12,  8,  9])

In [109]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [110]:
ar.T       convert row to columan to row

SyntaxError: invalid syntax (675454937.py, line 1)

In [111]:
ar.flat

In [112]:
for item in flatiter :               # ,   ,, ,, ,,ny samjala
    print(item)

SyntaxError: invalid syntax (2279765280.py, line 1)

In [113]:
ar.ndim

2

In [114]:
ar.size # show item in array

9

In [115]:
ar.nbytes

36

In [116]:
ar.argmax()

6

In [117]:
ar.min()

0

In [118]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [119]:
ar.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [120]:
ar.argmin(axis=1)

array([0, 0, 2], dtype=int64)

In [121]:
ar+myarr

ValueError: operands could not be broadcast together with shapes (3,3) (5,) 

In [6]:
import numpy as np 

In [8]:
a=np.zeros((5,5))
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [3]:
import numpy as np 
arr = np.array([1,2,3])
print(np.cumsum(arr))  #numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

[1 3 6]


In [5]:
ab = [1,1,"abhay","pratikasha"]

In [9]:
ab

[1, 1, 'abhay', 'pratikasha', 'abhay']

In [8]:
ab.append("abhay")

In [10]:
ab= ("ab",1,"pra",1)

In [11]:
ab

('ab', 1, 'pra', 1)

In [14]:
ab= {1,1,2,3}

In [15]:
ab

{1, 2, 3}